# test-props00.properties - good properties for VS specimen.
#                         - See SpecimenExtractor.docx for details
# Note: height measurements (last column) are extended a little bit. 

page1.row1.rect =  36,  36, 540,   23
page1.row2.rect =  36,  64, 540,   64
page1.row3.rect =  36, 126, 540,  135
page1.col1.rect =  36, 261, 180,  705
page1.col2.rect = 216, 261, 180,  705
page1.col3.rect = 396, 261, 180,  705
page2.col1.rect =  36,  36, 180,  940
page2.col2.rect = 216,  36, 180,  940
page2.col3.rect = 396,  36, 180,  940